version: '3.4'
services:
  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    volumes:
      - ./storage:/opt/app/storage
    environment:
      HOUDINI_NODESHAPE_CONVERTER_STOREAGEDIR: /opt/app/storage
    ports:
      - "8001:8000"
x-docker-remote:
  project:
    name: houdini-nodeshape-converter
